const quizData = {
    python: [
        { question: "¿Cuál es la principal diferencia entre una lista y una tupla en Python?", options: ["Las listas son inmutables, las tuplas son mutables.", "Las listas son mutables, las tuplas son inmutables.", "Las listas solo almacenan strings, las tuplas solo números.", "No hay diferencia, son sinónimos sintácticos."], correctAnswer: 1, explanation: "Las listas en Python pueden modificarse (mutables), mientras que las tuplas no (inmutables)." },
        { question: "¿Qué hace el método .append() en una lista?", options: ["Añade al principio.", "Elimina el último elemento.", "Añade un elemento al final.", "Ordena alfabéticamente."], correctAnswer: 2, explanation: "El método .append() modifica la lista original agregando el elemento al final." },
        { question: "¿Cuál es el resultado de evaluar `bool(\"\")` en Python?", options: ["True", "False", "None", "Error"], correctAnswer: 1, explanation: "Los strings vacíos se evalúan como False (Falsy)." },
        { question: "¿Qué palabra clave se usa para manejar excepciones?", options: ["try ... catch", "do ... except", "try ... except", "catch ... finally"], correctAnswer: 2, explanation: "En Python se utiliza el bloque try/except." },
        { question: "¿Qué estructura de datos subyacente usan los diccionarios?", options: ["Árboles binarios", "Tablas Hash", "Listas enlazadas", "Grafos"], correctAnswer: 1, explanation: "Están implementados usando Tablas Hash, permitiendo búsquedas muy rápidas O(1)." },
        { question: "¿Qué función se usa para obtener la longitud de una lista?", options: ["length()", "size()", "count()", "len()"], correctAnswer: 3, explanation: "La función incorporada len() devuelve el número de elementos." },
        { question: "¿Cuál es la forma correcta de definir una función?", options: ["function myFunc()", "def myFunc():", "void myFunc()", "create myFunc()"], correctAnswer: 1, explanation: "En Python se usa la palabra reservada 'def' seguida del nombre y dos puntos." },
        { question: "¿Qué hace la instrucción 'yield'?", options: ["Termina la función.", "Devuelve un valor y suspende la ejecución de la función (Generador).", "Lanza una excepción.", "Pausa el hilo actual por un segundo."], correctAnswer: 1, explanation: "'yield' convierte la función en un generador, permitiendo iterar valores de uno en uno." },
        { question: "¿Cómo se importa el módulo matemático integrado?", options: ["include math", "import math", "using math", "require('math')"], correctAnswer: 1, explanation: "Se utiliza la palabra clave 'import'." },
        { question: "¿Qué significa que Python sea de tipado dinámico?", options: ["Las variables no pueden cambiar de tipo.", "El tipo de variable se determina en tiempo de ejecución.", "Todas las variables son strings internamente.", "Es necesario declarar el tipo antes de usar la variable."], correctAnswer: 1, explanation: "No se requiere declarar el tipo de variable; el intérprete lo infiere en tiempo de ejecución." }
    ],
    java: [
        { question: "¿Cuál es el tamaño en bytes de un 'int' en Java?", options: ["2 bytes", "4 bytes", "8 bytes", "Depende del sistema"], correctAnswer: 1, explanation: "En Java, el 'int' siempre ocupa 4 bytes (32 bits)." },
        { question: "¿Qué significa 'static' en un método?", options: ["No puede ser sobreescrito.", "Pertenece a la clase y no a las instancias.", "Su valor no cambiará.", "Solo para un solo hilo."], correctAnswer: 1, explanation: "Los métodos estáticos pertenecen a la clase." },
        { question: "¿Qué clase lee la entrada del usuario típicamente?", options: ["System.in", "ConsoleReader", "Scanner", "InputReader"], correctAnswer: 2, explanation: "La clase Scanner de java.util." },
        { question: "¿Es válida la herencia múltiple de clases en Java?", options: ["Sí, extiende múltiples.", "No, pero implementa múltiples interfaces.", "Solo en abstractas.", "Sí, con 'implements'."], correctAnswer: 1, explanation: "No soporta herencia múltiple de clases para evitar el problema del diamante." },
        { question: "¿Qué pasa si no inicializamos una variable de instancia int?", options: ["Error de compilación.", "Valor aleatorio.", "Inicializa en 0.", "NullPointerException."], correctAnswer: 2, explanation: "Las variables de instancia numéricas primitivas se inicializan a 0 por defecto." },
        { question: "¿Qué modificador de acceso permite visibilidad solo dentro del mismo paquete?", options: ["public", "private", "protected", "default (sin modificador)"], correctAnswer: 3, explanation: "Si no se especifica (default/package-private), solo las clases del mismo paquete pueden acceder." },
        { question: "¿Cuál es la clase raíz de la que heredan todas las demás en Java?", options: ["Main", "Object", "System", "Base"], correctAnswer: 1, explanation: "Toda clase en Java hereda directa o indirectamente de java.lang.Object." },
        { question: "¿Qué es el 'Garbage Collector'?", options: ["Una clase para borrar archivos.", "Un proceso automático que libera memoria de objetos sin referencias.", "Un patrón de diseño.", "Una herramienta para limpiar código muerto."], correctAnswer: 1, explanation: "Libera memoria automáticamente destruyendo los objetos que ya no son accesibles." },
        { question: "¿Cómo se llama el proceso de múltiples constructores en la misma clase con distintos parámetros?", options: ["Sobreescritura (Overriding)", "Polimorfismo", "Sobrecarga (Overloading)", "Encapsulamiento"], correctAnswer: 2, explanation: "La sobrecarga permite tener múltiples métodos o constructores con el mismo nombre pero diferente firma." },
        { question: "¿Qué estructura de control es equivalente a un IF múltiple?", options: ["while", "for", "switch", "do-while"], correctAnswer: 2, explanation: "La sentencia 'switch' evalúa una variable contra múltiples casos." }
    ],
    linux: [
        { question: "¿Comando para listar todos los archivos, ocultos y en formato largo?", options: ["ls -a", "ls -l", "ls -la", "dir -all"], correctAnswer: 2, explanation: "'-l' es formato largo y '-a' incluye ocultos." },
        { question: "¿Qué comando busca un patrón de texto dentro de archivos?", options: ["find", "grep", "search", "locate"], correctAnswer: 1, explanation: "grep busca patrones mediante expresiones regulares." },
        { question: "En los permisos 'chmod 755', ¿qué significa el '7'?", options: ["Lectura y Escritura para propietario.", "Lectura, Escritura y Ejecución para propietario.", "Ejecución para todos.", "Permisos totales para el grupo."], correctAnswer: 1, explanation: "7 = Lectura(4) + Escritura(2) + Ejecución(1) para el Propietario." },
        { question: "¿Qué directorio guarda los archivos de configuración?", options: ["/bin", "/home", "/etc", "/var"], correctAnswer: 2, explanation: "/etc es el estándar para configuraciones." },
        { question: "¿Cómo matas un proceso (PID) de forma forzosa?", options: ["stop <PID>", "kill -9 <PID>", "end <PID>", "exit <PID>"], correctAnswer: 1, explanation: "kill -9 envía la señal SIGKILL." },
        { question: "¿Qué comando muestra el espacio libre en disco?", options: ["free", "du", "df", "mem"], correctAnswer: 2, explanation: "df (disk free) muestra el espacio libre en los sistemas de archivos montados." },
        { question: "¿Qué hace el comando 'pwd'?", options: ["Pide una contraseña.", "Muestra la ruta del directorio actual.", "Cambia de directorio.", "Imprime un archivo."], correctAnswer: 1, explanation: "'pwd' significa Print Working Directory." },
        { question: "¿Cómo cambias al usuario root?", options: ["su", "switch root", "sudo", "Ambas 'su' o comandos con 'sudo'"], correctAnswer: 3, explanation: "Se usa 'su' para cambiar de usuario a root o 'sudo' para ejecutar comandos con sus privilegios." },
        { question: "¿Qué archivo configura los servidores DNS en Linux?", options: ["/etc/network", "/etc/hosts", "/etc/resolv.conf", "/var/dns"], correctAnswer: 2, explanation: "El archivo /etc/resolv.conf contiene los nombres de servidores DNS a utilizar." },
        { question: "¿Comando para crear un directorio?", options: ["makedir", "mkdir", "create", "newdir"], correctAnswer: 1, explanation: "El comando 'mkdir' (make directory) crea nuevas carpetas." }
    ],
    javascript: [
        { question: "¿Resultado de 'typeof null'?", options: ["'null'", "'undefined'", "'object'", "Error"], correctAnswer: 2, explanation: "Por un error histórico, devuelve 'object'." },
        { question: "¿Método para convertir un string JSON en un objeto JavaScript?", options: ["JSON.parse()", "JSON.stringify()", "JSON.toObject()", "Object.fromJSON()"], correctAnswer: 0, explanation: "JSON.parse() analiza la cadena a un objeto." },
        { question: "¿Diferencia entre '==' y '==='?", options: ["Ninguna.", "Solo compara valor, compara valor y tipo.", "Compara valor y tipo, compara solo valor (coerción).", "Números vs strings."], correctAnswer: 2, explanation: "'===' es igualdad estricta sin coerción de tipos." },
        { question: "¿Qué es un Closure?", options: ["Cerrar el navegador.", "Garbage Collection.", "Función que recuerda el entorno en el que fue creada.", "Final de un script."], correctAnswer: 2, explanation: "Combina una función y el ámbito léxico donde se declaró." },
        { question: "¿Declarar variables con ámbito de bloque?", options: ["var y let", "let y const", "var y const", "solo let"], correctAnswer: 1, explanation: "'let' y 'const' son de ES6 y tienen ámbito de bloque." },
        { question: "¿Qué objeto representa el documento HTML en el navegador?", options: ["Window", "Document", "Screen", "Navigator"], correctAnswer: 1, explanation: "El objeto Document es la raíz del DOM." },
        { question: "¿Qué palabra clave se usa para funciones asíncronas?", options: ["async", "await", "promise", "defer"], correctAnswer: 0, explanation: "La palabra 'async' declara una función asíncrona." },
        { question: "¿Cómo se llama el proceso donde eventos de hijos se propagan a sus padres?", options: ["Event Capturing", "Event Bubbling", "Event Hoisting", "Event Delegation"], correctAnswer: 1, explanation: "En Event Bubbling, el evento se propaga desde el elemento más profundo hasta la raíz." },
        { question: "¿Cuál es el valor por defecto de una variable no inicializada?", options: ["null", "0", "undefined", "NaN"], correctAnswer: 2, explanation: "Si declaras una variable pero no le asignas valor, es 'undefined'." },
        { question: "¿Qué método de los arrays crea un nuevo array con los resultados de la llamada a una función en cada elemento?", options: ["forEach()", "map()", "filter()", "reduce()"], correctAnswer: 1, explanation: "map() transforma cada elemento y retorna el nuevo array." }
    ],
    sql: [
        { question: "¿Comando para extraer datos?", options: ["EXTRACT", "GET", "OPEN", "SELECT"], correctAnswer: 3, explanation: "SELECT selecciona o extrae datos." },
        { question: "¿Cláusula para filtrar registros?", options: ["FILTER", "WHERE", "HAVING", "ORDER BY"], correctAnswer: 1, explanation: "WHERE se usa para extraer bajo una condición." },
        { question: "¿Qué JOIN devuelve filas izquierdas y coincidentes derechas?", options: ["INNER JOIN", "RIGHT JOIN", "LEFT JOIN", "FULL JOIN"], correctAnswer: 2, explanation: "LEFT JOIN prioriza la tabla izquierda." },
        { question: "¿Función agregada para contar filas?", options: ["SUM()", "TOTAL()", "COUNT()", "AVG()"], correctAnswer: 2, explanation: "COUNT() devuelve el número de filas." },
        { question: "¿Comando para actualizar datos existentes?", options: ["MODIFY", "SAVE", "UPDATE", "CHANGE"], correctAnswer: 2, explanation: "UPDATE modifica registros." },
        { question: "¿Qué comando elimina una tabla completa junto con su estructura?", options: ["DELETE TABLE", "REMOVE TABLE", "DROP TABLE", "CLEAR TABLE"], correctAnswer: 2, explanation: "DROP TABLE elimina los datos y la definición de la tabla en el esquema." },
        { question: "¿Cuál es la diferencia entre DELETE y TRUNCATE?", options: ["Son sinónimos.", "DELETE es más rápido.", "TRUNCATE elimina todas las filas sin registrar cada eliminación en el log, siendo más rápido.", "DELETE borra columnas."], correctAnswer: 2, explanation: "TRUNCATE es una operación DDL súper rápida para vaciar una tabla completa." },
        { question: "¿Qué significa SQL?", options: ["Structured Query Language", "Strong Question Language", "System Query Logic", "Simple Query Language"], correctAnswer: 0, explanation: "Structured Query Language." },
        { question: "¿Para qué sirve GROUP BY?", options: ["Para ordenar resultados.", "Para agrupar filas que tienen los mismos valores en filas de resumen.", "Para unir tablas.", "Para crear usuarios."], correctAnswer: 1, explanation: "Se utiliza frecuentemente con funciones agregadas (COUNT, MAX, MIN, SUM, AVG)." },
        { question: "¿Qué restricción asegura que una columna no contenga valores nulos y sea única?", options: ["UNIQUE", "PRIMARY KEY", "FOREIGN KEY", "NOT NULL"], correctAnswer: 1, explanation: "PRIMARY KEY (Llave Primaria) identifica unívocamente cada fila." }
    ],
    htmlcss: [
        { question: "¿Qué significa HTML?", options: ["Hyper Text Markup Language", "High Tech Machine Language", "Hyperlinks and Text Markup Language", "Home Tool Markup Language"], correctAnswer: 0, explanation: "Significa Hyper Text Markup Language." },
        { question: "¿Cuál es la etiqueta correcta para el encabezado más grande?", options: ["<heading>", "<h1>", "<h6>", "<head>"], correctAnswer: 1, explanation: "<h1> es el nivel de encabezado principal y más grande." },
        { question: "¿Qué propiedad de CSS cambia el color del texto?", options: ["text-color", "fgcolor", "color", "font-color"], correctAnswer: 2, explanation: "La propiedad 'color' define el color de la fuente." },
        { question: "¿Cómo se selecciona un elemento con id 'demo' en CSS?", options: [".demo", "#demo", "*demo", "demo"], correctAnswer: 1, explanation: "El símbolo '#' se utiliza para apuntar a un ID." },
        { question: "¿Qué propiedad cambia el color de fondo en CSS?", options: ["color", "bgcolor", "background-color", "background-image"], correctAnswer: 2, explanation: "'background-color' se usa para el color de fondo." },
        { question: "¿En HTML, qué atributo se usa para especificar una ruta a un enlace?", options: ["href", "src", "link", "url"], correctAnswer: 0, explanation: "El atributo 'href' (Hypertext REFerence) indica el destino del ancla." },
        { question: "¿Qué propiedad de CSS se usa para el modelo Flexbox?", options: ["display: flex;", "float: flex;", "position: flex;", "layout: flex;"], correctAnswer: 0, explanation: "'display: flex' activa el contexto de flexbox." },
        { question: "¿Qué etiqueta HTML5 se usa para el pie de página?", options: ["<bottom>", "<foot>", "<footer>", "<end>"], correctAnswer: 2, explanation: "<footer> define el pie de un documento o sección." },
        { question: "¿Qué es el 'Box Model' en CSS?", options: ["Cajas de texto 3D.", "Un modelo de diseño que envuelve cada elemento HTML (Márgenes, Bordes, Relleno y Contenido).", "Un framework como Bootstrap.", "Una etiqueta HTML."], correctAnswer: 1, explanation: "El modelo de caja define cómo se genera el espacio alrededor de los elementos HTML." },
        { question: "¿Cómo hacer que un diseño sea 'Responsive' a móviles?", options: ["Haciendo la fuente más grande.", "Usando Media Queries (@media).", "Usando tablas en HTML.", "Borrando imágenes."], correctAnswer: 1, explanation: "Las @media queries permiten aplicar estilos según las características del dispositivo." }
    ],
    git: [
        { question: "¿Comando para iniciar un repositorio local vacío?", options: ["git start", "git init", "git new", "git create"], correctAnswer: 1, explanation: "git init inicializa un nuevo repositorio." },
        { question: "¿Qué comando muestra el estado de los archivos (modificados, en stage)?", options: ["git info", "git log", "git status", "git show"], correctAnswer: 2, explanation: "git status muestra el árbol de trabajo actual." },
        { question: "¿Cómo añades todos los cambios al 'staging area'?", options: ["git add .", "git commit all", "git stage *", "git push all"], correctAnswer: 0, explanation: "git add . añade todo el directorio actual." },
        { question: "¿Para qué sirve 'git clone'?", options: ["Para copiar una rama.", "Para descargar un repositorio remoto a tu máquina local.", "Para crear un backup.", "Para fusionar commits."], correctAnswer: 1, explanation: "Clona un repositorio remoto en tu sistema local." },
        { question: "¿Comando para enviar los commits locales al repositorio remoto?", options: ["git upload", "git send", "git push", "git pull"], correctAnswer: 2, explanation: "git push actualiza las referencias remotas usando las locales." },
        { question: "¿Qué comando crea una nueva rama y se cambia a ella?", options: ["git branch new", "git checkout -b <nombre>", "git switch new", "git make-branch"], correctAnswer: 1, explanation: "git checkout -b combina crear la rama y cambiarte a ella." },
        { question: "¿Qué hace 'git pull'?", options: ["Descarga los cambios remotos e integra (fusiona) con tu rama actual.", "Solo descarga sin integrar.", "Sube tus cambios.", "Borra la rama remota."], correctAnswer: 0, explanation: "git pull es la combinación de git fetch y git merge." },
        { question: "¿Qué es un 'merge conflict'?", options: ["Cuando falla el servidor de GitHub.", "Cuando dos ramas tienen cambios incompatibles en la misma línea de código.", "Un error de sintaxis en el código.", "Cuando no tienes internet."], correctAnswer: 1, explanation: "Ocurre cuando Git no puede fusionar automáticamente los cambios de dos ramas." },
        { question: "¿Comando para ver el historial de commits?", options: ["git history", "git log", "git list", "git commits"], correctAnswer: 1, explanation: "git log muestra el historial completo de los commits realizados." },
        { question: "¿Qué archivo ignoran los archivos y directorios no deseados?", options: [".gitignore", "ignore.txt", ".nocommit", ".gitconfig"], correctAnswer: 0, explanation: "El archivo .gitignore le dice a Git qué archivos no debe rastrear." }
    ]
};
